### ISSUE TITLE
how to change e_wk in QP form???

### ISSUE THREAD

**Issue by niteofhunter** [YanranDing/RF-MPC#3]
I read your journal publication "Representation-Free Model Predictive Control for Dynamic Motions in Quadrupeds" very well and I have a question about this paper.

in your publication, we should make QP form with the cost function

![image](https://user-images.githubusercontent.com/10339608/189356128-708146fc-9d0d-40ee-b757-7977eb4f089f.png)

but the problem arose in the cost of angular velocity 

![image](https://user-images.githubusercontent.com/10339608/189356220-7bed5a3f-ea03-42d2-816f-1cad9c8a064d.png)

I think R_k is the unknown matrix that we should get from MPC.

So, I can't understand how to change e_Wk (30) to the QP form 

![image](https://user-images.githubusercontent.com/10339608/189356911-f6850816-a2bd-4e9a-8b5d-f984addd89cf.png)

I also saw your code here to find out how to do that.

However, this code shows only situations in which, Wdk = [0,0,0] (not gaiting) and RtkRdkWdk = [0,dth0,0] (I don't know why it's derived)

![image](https://user-images.githubusercontent.com/10339608/189356997-9b632694-1f90-454c-b2b2-ee2f4026125f.png)

Could you show me how to change e_Wk to QP form???

Thank you ^^

P.S. As Your publication give many backgrounds, it is very good for novices like me ^^

**Comment by YanranDing** [comment]
Hi Jae-Bong,

That's a good question. Please take a look at the file "fcn_get_QP_form_eta.m"
![image](https://user-images.githubusercontent.com/45923496/189358103-92374597-376d-4bd6-8945-0e25894f308d.png)

Line 63,69 are the setup for the cost on the angular velocity.
In (30), you are right Rk is unknown and thus part of the decision variables. 
But e_wk is in affine form of the variables, and its 2-norm can be incorporated in QP form.
Wdk is the desired angular velocity, which does not necessarily need to be [0,0,0]

![image](https://user-images.githubusercontent.com/45923496/189358171-8455fec7-ae5c-4c5b-af30-26aef4dbdabe.png)

Here, Xt is the initial condition.

Hope it helps!

Best,
Yanran

**Comment by niteofhunter** [comment]
Thank you for your reply ^^

But, I can't understand what's the meaning of "its 2-norm can be incorporated in QP form."

Is it mean the e_wk can be represented in below form???


![20220909_231347](https://user-images.githubusercontent.com/10339608/189371372-0c79ec56-3e58-4031-b52f-d6f55950bdd2.jpg)

I think it is also impossible, and your publication said 

x_k := [p_k, p_k_dot, xi, w]. 

not including Rk 


Thank you.

**Comment by niteofhunter** [comment]
Thank you. ^^

**Comment by niteofhunter** [comment]
I also saw "fcn_get_QP_form_eta.m".

but in this file, Rt is gotten from input variable

![image](https://user-images.githubusercontent.com/10339608/189664934-4223f5d3-991c-48a7-9c18-b90bffcb343b.png)
